### ISSUE TITLE
Rewrite of this Module

### ISSUE THREAD

**Issue by bobapple** [Icinga/puppet-icinga2-legacy#226]
As you may have noticed, there is a huge gap between the master branch and a branch called ‘development’. The module has evolved historically during committs of many contributers with fixes and features for many things.

We, the Icinga Project, came to the point where we had to decide how we want to proceed with this module. For us it is important that our integrations work for as many users as possible. Configuration management and especially Puppet is, and has been, one of the most important integrations for us. With the current module we felt like it is not coming to an end, where “end” is a final v1.0.0. So much work has been done and still there is so much to do to get a clean, well documented and multi platform capable module that can be used for many different scenarios. 

I decided that to achieve this goal, a complete rewrite of the module is the best solution. This decision was not easy and has not been made in a hasty situation. Rather, it took me many hours of reviews, meetings and discussions with many people before I came to that point. 

** Where’s the code?
There is already code and there is a roadmap. You can find both of them here:
- https://github.com/Icinga/puppet-icinga2-rewrite
- https://dev.icinga.org/projects/puppet-icinga2-rewrite/roadmap

** What is happening with the current module?
The current module will be renamed to ‘puppet-icinga2-legacy’ and will be available on GitHub for at least the next couple of months. Maintenance for this module will be discontinued as soon as there is a v1.0.0 of the new module.

I want to invite you to continue your appreciated work in a new environment. Please find all information about development and contributing in the repositories README.md and CONTRIBUTING.md

**Comment by zachfi** [comment]
Thank you for the efforts @bobapple.

**Comment by TwizzyDizzy** [comment]
Hi folks,

one quick question concerning the rewrite: We're starting to implement Icinga 2 in our environment in the coming weeks. That being said, what would you think would be the wisest course of actions:
- for now, use **puppet-icinga2/develop**, then switch to **puppet-icinga2-rewrite** ?

Will the switch from **puppet-icinga2/develop** to **puppet-icinga2-rewrite** be straightforward?

Do you have any idea, when the [influxdb-writer feature](https://github.com/TheFlyingCorpse/puppet-icinga2/tree/feature/infludbwriter) will be merged to **puppet-icinga2-rewrite**?

Cheers
Thomas

**Comment by bobapple** [comment]
Hi Thomas,

I think the best solution for you is to start directly with icinga2-puppet-rewrite. The InfluxDB feature is already implemented as of v05.0.

**Comment by bobapple** [comment]
I renamed this Repository to 'puppet-icinga2-legacy'
